from pydantic import BaseModel, Field
from typing import List, Optional, Literal, Union

class Keypoint(BaseModel):
    x: float
    y: float
    z: Optional[float] = None
    score: Optional[float] = None

class WorldKeypoint(BaseModel):
    x: float
    y: float
    z: float
    score: Optional[float] = None

class Person(BaseModel):
    id: str
    keypoints: List[Keypoint]
    worldKeypoints: Optional[List[WorldKeypoint]] = None

class Frame(BaseModel):
    t_ms: float
    mode: Literal["holistic", "movenet"]
    people: List[Person]

class VideoInfo(BaseModel):
    width: int
    height: int

class RecordingCreate(BaseModel):
    # ID is optionally provided by client or generated by backend. 
    # requirement says "POST /recordings (body: recording JSON, returns {id})"
    # We will let backend generate ID if missing, or use client's if provided (UUIDv4)
    id: Optional[str] = None
    created_at_iso: str
    fps: int = 24
    video: VideoInfo
    mode: str
    requested_people: int
    frames: List[Frame]

class RecordingSummary(BaseModel):
    id: str
    created_at_iso: str
    mode: str
    duration_s: float
